on:
    push:
        branches: ["main"]

env:
    IMAGE_NAME: reactjs-image-gcp

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set TAG from commit SHA
              run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}

            - name: Build Docker Image
              run: docker build -t ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

            - name: Push Docker Image
              run: docker push ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

            - name: Logout from Docker Registry
              if: always()
              run: docker logout

    deploy-service:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set TAG from commit SHA
              run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

            - name: Deploy via SSH to GCP VM
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.GCP_IP }}
                  username: ${{ secrets.GCP_USER }}
                  key: ${{ secrets.GCP_PRIVATE_KEY }}
                  envs: TAG
                  script: |
                      echo "Current location is $(pwd)"

                      echo "Stopping old container..."
                      docker stop my-app || true
                      docker rm my-app || true

                      echo "Pulling updated image..."
                      docker pull "${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"

                      echo "Running new container..."
                      docker run -d \
                        --name my-app \
                        -p 3000:80 \
                        "${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
